sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLEbUwcAyNbcsn7ZeoX
    access-key-secret: 16rCZgIjUv1pqIdiPnn9DpmeBHlFAN
    bucket-name: xiaowanbaobao