sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLEbUwcAyNbcsn7ZeoX
    access-key-secret: 16rCZgIjUv1pqIdiPnn9DpmeBHlFAN
    bucket-name: xiaowanbaobao
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx03cbdafcef322478
    secret: 3400844dcac8322a2a1a7530966a7c94